CREATE TABLE SHUUSHI
(
    SHUUSHI_NO NUMBER(12) PRIMARY KEY,
    USER_NO VARCHAR2(20) NOT NULL,
    RACE_DATE VARCHAR2(10),
    COURSE_NO NUMBER(2),
    RACE_NO NUMBER(2),
    KENSHU_NO NUMBER(1),
    KOUNYUU_KINGAKU NUMBER(8) NOT NULL,
    HARAIMODOSHI NUMBER(8) NOT NULL,
    INS_DATE DATE,
    UPD_DATE DATE
);