CREATE TABLE PASSWORD_RESET_TOKEN
(
    RESET_TOKEN_ID INTEGER PRIMARY KEY,
    USER_NO VARCHAR(10) NOT NULL,
    TOKEN_HASH CHAR(64) NOT NULL UNIQUE,
    EXPIRES_AT TIMESTAMP NOT NULL,
    USED_AT TIMESTAMP,
    REVOKED_AT TIMESTAMP,
    INS_DATE TIMESTAMP NOT NULL
);