CREATE TABLE USERS
(
    USER_NO VARCHAR2(10) PRIMARY KEY,
    USER_ID VARCHAR2(30) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    MAIL_ADDRESS VARCHAR2(255) NOT NULL,
    DEL_FLG CHAR(1),
    LAST_LOGIN_DATE DATE,
    INS_DATE DATE,
    UPD_DATE DATE
);