CREATE TABLE SHUUSHI
(
    SHUUSHI_NO NUMBER(12) PRIMARY KEY,
    USER_NO VARCHAR2(20) NOT NULL,
    KENSHU_NO VARCHAR2(255),
    RACE_DATE VARCHAR2(10),
    COURSE_NO CHAR(1),
    RACE_NO VARCHAR2(2),
    KOUNYUU_KINGAKU NUMBER(8) NOT NULL,
    HARAIMODOSHI NUMBER(8) NOT NULL,
    INS_DATE DATE,
    UPD_DATE DATE
);