CREATE TABLE SHUUSHI
(
    SHUUSHI_NO INTEGER PRIMARY KEY,
    USER_NO VARCHAR(20) NOT NULL,
    RACE_DATE VARCHAR(10),
    COURSE_NO SMALLSERIAL,
    RACE_NO SMALLSERIAL,
    KENSHU_NO SMALLSERIAL,
    KOUNYUU_KINGAKU INTEGER NOT NULL,
    HARAIMODOSHI INTEGER NOT NULL,
    DEL_FLG CHAR(1),
    INS_DATE TIMESTAMP,
    UPD_DATE TIMESTAMP
);