CREATE TABLE PASSWORD_RESET_TOKEN
(
    RESET_TOKEN_ID INTEGER PRIMARY KEY,
    USER_NO VARCHAR(10) NOT NULL,
    TOKEN_HASH CHAR(64) NOT NULL UNIQUE,
    EXPIRES_AT TIMESTAMP NOT NULL,
    USED_AT TIMESTAMP,
    REVOKED_AT TIMESTAMP,
    INS_DATE TIMESTAMP

    CONSTRAINT CK_PASSWORD_RESET_TOKEN_EXPIRATION
        CHECK (EXPIRES_AT > INS_DATE),

    CONSTRAINT CK_PASSWORD_RESET_TOKEN_USED
        CHECK (USED_AT IS NULL OR USED_AT >= INS_DATE),

    CONSTRAINT CK_PASSWORD_RESET_TOKEN_REVOKED
        CHECK (REVOKED_AT IS NULL OR REVOKED_AT >= INS_DATE)
);