CREATE TABLE USERS
(
    USER_NO VARCHAR(10) PRIMARY KEY,
    USER_ID VARCHAR(30) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    MAIL_ADDRESS VARCHAR(255) NOT NULL UNIQUE,
    DEL_FLG CHAR(1),
    INS_DATE TIMESTAMP,
    UPD_DATE TIMESTAMP
);
